name: aur-publish

on:
  push:
    branches:
      - main

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8.1

      - name: Publish zeronsd to the AUR
        if: contains(steps.changed-files.outputs.modified_files, 'zeronsd/PKGBUILD')
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: zeronsd
          pkgbuild: ./zeronsd/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519

      - name: Publish zerotier-systemd-manager to the AUR
        if: contains(steps.changed-files.outputs.modified_files, 'zerotier-systemd-manager-bin/PKGBUILD')
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: zerotier-systemd-manager-bin
          pkgbuild: ./zerotier-systemd-manager-bin/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519

      - name: Publish zerotier-systemd-manager-git to the AUR
        if: contains(steps.changed-files.outputs.modified_files, 'zerotier-systemd-manager-git/PKGBUILD')
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: zerotier-systemd-manager-git
          pkgbuild: ./zerotier-systemd-manager-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
