name: aur-publish-zerotier-systemd-manager-bin

on:
  push:
    branches:
      - main
    paths:
      - 'zerotier-systemd-manager-bin/PKGBUILD'

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish zerotier-systemd-manager-bin to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.4.1
        with:
          pkgname: zerotier-systemd-manager-bin
          pkgbuild: ./zerotier-systemd-manager-bin/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
