name: aur-publish-zerotier-systemd-manager-git

on:
  push:
    branches:
      - main
    paths:
      - 'zerotier-systemd-manager-git/PKGBUILD'

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish zerotier-systemd-manager-git to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.0
        with:
          pkgname: zerotier-systemd-manager-git
          pkgbuild: ./zerotier-systemd-manager-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
